// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Global.Models
{

    public class AndroidWrappingDetail
    {

        [JsonProperty("unwrapped_binary_path")]
        public string UnwrappedBinaryPath { get; set; }

        [JsonProperty("wrapped_binary_path")]
        public string WrappedBinaryPath { get; set; }

        [JsonProperty("wrap_script_url")]
        public string WrapScriptUrl { get; set; }

        [JsonProperty("user_name")]
        public string UserName { get; set; }

        [JsonProperty("password")]
        public string Password { get; set; }
    }

}
