// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Global.Models
{

    public class AuthenticationPriority
    {

        [JsonProperty("priority_zero")]
        public int PriorityZero { get; set; }

        [JsonProperty("priority_one")]
        public int PriorityOne { get; set; }

        [JsonProperty("priority_two")]
        public int PriorityTwo { get; set; }

        [JsonProperty("priority_three")]
        public int PriorityThree { get; set; }
    }

}
