// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Global.Models
{

    public class ExternalUserDetailsDetail
    {

        [JsonProperty("host")]
        public string Host { get; set; }

        [JsonProperty("protocol")]
        public string Protocol { get; set; }

        [JsonProperty("external_url")]
        public string ExternalUrl { get; set; }

        [JsonProperty("method")]
        public string Method { get; set; }

        [JsonProperty("external_system_port")]
        public int ExternalSystemPort { get; set; }

        [JsonProperty("external_system_timeout")]
        public int ExternalSystemTimeout { get; set; }
    }

}
