// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Global.Models
{

    public class SsoDetail
    {

        [JsonProperty("cache_credential_period")]
        public string CacheCredentialPeriod { get; set; }

        [JsonProperty("ios_sso_agent")]
        public string IosSsoAgent { get; set; }

        [JsonProperty("android_sso_agent")]
        public string AndroidSsoAgent { get; set; }

        [JsonProperty("encryption_algorithm")]
        public string EncryptionAlgorithm { get; set; }

        [JsonProperty("public_key")]
        public string PublicKey { get; set; }

        [JsonProperty("certificate_name")]
        public object CertificateName { get; set; }

        [JsonProperty("is_ownkey")]
        public bool IsOwnkey { get; set; }

        [JsonProperty("aes_salt")]
        public string AesSalt { get; set; }

        [JsonProperty("extend_token_period")]
        public bool ExtendTokenPeriod { get; set; }

        [JsonProperty("cache_credential")]
        public bool CacheCredential { get; set; }

        [JsonProperty("domain")]
        public string Domain { get; set; }

        [JsonProperty("sso_applicable_agent")]
        public string SsoApplicableAgent { get; set; }

        [JsonProperty("public_key_extension")]
        public string PublicKeyExtension { get; set; }

        [JsonProperty("logout_url")]
        public string LogoutUrl { get; set; }

        [JsonProperty("cert_pwd")]
        public string CertPwd { get; set; }

        [JsonProperty("modified_by")]
        public string ModifiedBy { get; set; }

        [JsonProperty("modified_date")]
        public string ModifiedDate { get; set; }
    }

}
