// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Global.Models
{

    public class Test4
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("sso_details")]
        public IList<SsoDetail> SsoDetails { get; set; }

        [JsonProperty("age")]
        public int Age { get; set; }
    }

}
